# Generated by Django 5.2.3 on 2025-06-25 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='原始網址')),
                ('short_url', models.CharField(max_length=20, unique=True, verbose_name='短網址代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密碼（可選）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
        ),
    ]
