# Generated by Django 5.2.3 on 2025-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0002_utm'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備註說明'),
        ),
    ]
