# Generated by Django 5.2.3 on 2025-06-30 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0003_shorturl_remarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorturls', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AlterField(
            model_name='utm',
            name='short_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utm', to='shorturls.shorturl'),
        ),
    ]
